const descriptions =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sed maximus risus. Pellentesque malesuada ligula sit amet erat sodales, in vulputate lectus facilisis. Duis cursus vestibulum elit a malesuada. Maecenas interdum, ligula nec efficitur malesuada, turpis arcu rutrum ligula, id vehicula libero mi eget ligula. Vivamus massa erat, interdum non blandit congue, accumsan at lorem. Integer ac hendrerit purus. Curabitur at ante egestas, efficitur erat non, vulputate turpis. Nam et lacus lacus. Pellentesque venenatis arcu at porttitor tempus. Sed luctus sapien sit amet ipsum molestie, ac commodo massa pretium. Integer sed gravida sapien. Aliquam et aliquam justo, quis consectetur velit.'

const testAuthorBiography =
  'Duis nec purus purus. Nam luctus erat sed diam euismod feugiat. Suspendisse vitae leo vitae nibh pellentesque varius. Sed vitae massa nec nibh venenatis pretium vel eu odio. Praesent lacinia vestibulum odio nec molestie. Sed in erat nunc. Quisque ornare pretium varius. Vivamus blandit tellus sed mauris ultricies'

const exampleBook = [
  {
    title: 'Mystery of the Ancient',
    genres: 'Mystery,Fiction,Adventure',
    ISBN: '9283749283749',
    publisherName: 'Epoch Publishers',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2018,
    description: 'A thrilling adventure that uncovers ancient secrets.',
    edition: 'first edition',
    pageCount: 280,
    img: '/assets/book-1.png',
  },
  {
    title: 'Whispers in the Dark',
    genres: 'Crime,Mystery,Drama',
    ISBN: '8273648273648',
    publisherName: 'Shadow Press',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2019,
    description: 'A suspenseful tale of intrigue and investigation.',
    edition: 'third edition',
    pageCount: 320,
    img: '/assets/book-2.png',
  },
  {
    title: 'Journey Through Hearts',
    genres: 'Romance,Fiction,Adventure',
    ISBN: '7364827364827',
    publisherName: 'Lovebound Publications',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2021,
    description: 'A romantic saga that spans continents and lifetimes.',
    edition: 'first edition',
    pageCount: 300,
    img: '/assets/book-3.png',
  },
  {
    title: 'Echoes of the Past',
    genres: 'Fiction,Drama,Others',
    ISBN: '9485739485739',
    publisherName: 'Timeless Reads',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2017,
    description: 'A historical novel that brings the past vividly to life.',
    edition: 'second edition',
    pageCount: 400,
    img: '/assets/book-4.png',
  },
  {
    title: 'The Last Laugh',
    genres: 'Comedy,Drama,Adventure',
    ISBN: '4857394857394',
    publisherName: 'Humor House',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2022,
    description: "A comedic journey that's sure to bring a smile.",
    edition: 'first edition',
    pageCount: 250,
    img: '/assets/book-5.png',
  },
  {
    title: 'Endless Time',
    genres: 'mystery,adventure',
    ISBN: '1223344555667',
    publisherName: 'Peak Publishers',
    author: '65bc83128eafa59d87017194',
    publishedYear: 1965,
    description: descriptions,
    edition: 'first edition',
    pageCount: 250,
    img: '/assets/book-6.png',
  },
  {
    title: 'Foovial',
    genres: 'fiction,drama',
    ISBN: '9988776655443',
    publisherName: 'EduBooks Publishing',
    author: '65bc83128eafa59d87017194',
    publishedYear: 1980,
    description: descriptions,
    edition: 'second edition',
    pageCount: 320,
    img: '/assets/book-7.png',
  },
  {
    title: 'Crime Mystery of Knowledge',
    genres: 'crime,mystery,thriller',
    ISBN: '1234567890123',
    publisherName: 'CodeCrafters',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2010,
    description: descriptions,
    edition: 'first edition',
    pageCount: 450,
    img: '/assets/book-8.png',
  },
  {
    title: 'Giggles and Groans',
    genres: 'comedy,drama',
    ISBN: '2123242526272',
    publisherName: 'GlobeTrotter Press',
    author: '65bc83128eafa59d87017194',
    publishedYear: 1972,
    description: descriptions,
    edition: 'fourth edition',
    pageCount: 200,
    img: '/assets/book-9.png',
  },
  {
    title: 'Laughter Line',
    genres: 'comedy,romance',
    ISBN: '3132333435363',
    publisherName: "Nature's Bounty Books",
    author: '65bc83128eafa59d87017194',
    publishedYear: 1998,
    description: descriptions,
    edition: 'first edition',
    pageCount: 175,
    img: '/assets/book-10.png',
  },
  {
    title: 'Shadows of Yesterday',
    genres: 'drama,mystery',
    ISBN: '4142434445464',
    publisherName: 'CosmoPress',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2001,
    description: descriptions,
    edition: 'third edition',
    pageCount: 300,
    img: '/assets/book-11.png',
  },
  {
    title: 'Whisper in the Shadows',
    genres: 'mystery,thriller',
    ISBN: '5152535455565',
    publisherName: 'GourmetPublishing',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2005,
    description: descriptions,
    edition: 'second edition',
    pageCount: 220,
    img: '/assets/book-12.png',
  },
  {
    title: 'Echos of Valor',
    genres: 'action,adventure',
    ISBN: '6162636465666',
    publisherName: 'InnerPeace Books',
    author: '65bc83128eafa59d87017194',
    publishedYear: 1990,
    description: descriptions,
    edition: 'first edition',
    pageCount: 190,
    img: '/assets/book-13.png',
  },
  {
    title: 'Strength of Knowledge',
    genres: 'fiction,education',
    ISBN: '7172737475767',
    publisherName: 'Visual Arts Press',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2015,
    description: descriptions,
    edition: 'first edition',
    pageCount: 210,
    img: '/assets/book-14.png',
  },
  {
    title: 'The Last Stand',
    genres: 'action,drama',
    ISBN: '8182838485868',
    publisherName: 'Final Hour Publications',
    author: '65bc83128eafa59d87017194',
    publishedYear: 2020,
    description: descriptions,
    edition: 'second edition',
    pageCount: 350,
    img: '/assets/book-15.png',
  },
]

export { exampleBook, testAuthorBiography, descriptions }
